Switching to a flat namespace!

diff --git a/.github/workflows/build-windows.yml b/.github/workflows/build-windows.yml
--- a/.github/workflows/build-windows.yml
+++ b/.github/workflows/build-windows.yml
@@ -11,6 +11,7 @@ jobs:
     name: Windows - ${{ matrix.python-version }}
     runs-on: windows-latest
     env:
+      COVERAGE_TOTAL: 60
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       fail-fast: false
@@ -24,17 +25,35 @@ jobs:
         python-version: ${{ matrix.python-version }}
         cache: 'pip'
         cache-dependency-path: setup.py
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         python -m pip install pytest pytest-cov coverage-badge coveralls pytest-benchmark
         pip install --verbose --editable .
-    - name: Test with pytest
+
+    - name: pytester-cov
+      id: pytester-cov
+      uses: programmingwithalex/pytester-cov@main
+      with:
+        pytest-root-dir: '.'
+        cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
+        cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
+        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+
+    - name: Coverage total fail - exit
+      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
       run: |
-        python -m pytest tests/ --cov=splex --benchmark-skip
-        coverage run --source=./src -m pytest tests/ --benchmark-skip
-        coverage json -o tests/test_results.json
-        coverage report -m
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+        exit 1
+
+  
+    # - name: Test with pytest
+    #   run: |
+    #     python -m pytest tests/ --cov=splex --benchmark-skip
+    #     coverage run --source=./src -m pytest tests/ --benchmark-skip
+    #     coverage json -o tests/test_results.json
+    #     coverage report -m
 
   # update_coverage:
   #   - if: matrix.os == 'windows-latest'  
